# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

eliminarNefropatia:
  url:   /eliminar-nefropatia
  param: { module: Nefropatia, action: delete }

crearNefropatia:
  url:   /crear-nefropatia
  param: { module: Nefropatia, action: new }

salvarNefropatia:
  url:   /salvar-nefropatia
  param: { module: Nefropatia, action: save }

editarNefropatia:
  url:   /editar-nefropatia
  param: { module: Nefropatia, action: edit }

manejarNefropatias:
  url:   /nefropatias
  param: { module: Nefropatia, action: index }

iniciarTrasplante:
  url:   /agregar-trasplante/:paciente_id/:pre_trasplante_id
  param: { module: Trasplante, action: new }

iniciarPreTrasplante:
  url:   /agregar-pre-trasplante/:paciente_id
  param: { module: Pacientepretrasplante, action: new }
  
crearMuertePaciente:
  url:   /muerte-paciente/:id
  param: { module: PacienteMuerte, action: new }

editarMuertePaciente:
  url:   /editar-muerte-paciente/:id
  param: { module: PacienteMuerte, action: edit }
  
editarEstadoPaciente:
  url:   /editar-estado-paciente/:id
  param: { module: estadoPaciente, action: edit }

editarPaciente:
  url:   /editar-paciente/:id
  param: { module: Pacientes, action: edit }
  
agregarPaciente:
  url:   /agregar-paciente.html
  param: { module: Pacientes, action: new }
  
consultas:
  url:   /consultas.html
  param: { module: consulta, action: index }

mostrarPaciente:
  url:   /paciente/:id
  param: { module: Pacientes, action: mostrar }

buscarPaciente:
  url:   /paciente
  param: { module: Pacientes, action: buscarAccion }
  
buscar:
  url:   /pacientes.html
  param: { module: Pacientes, action: buscar }
  
# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
